name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Netlify Deploy Action
        uses: South-Paw/action-netlify-deploy@v1.2.1

